version: '3.8'

services:
  puppeteer:
    image: "ghcr.io/puppeteer/puppeteer:latest" # Puppeteer with Chromium pre-installed
    volumes:
      - ./puppeteer:/app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    command: >
      sh -c "
        npm install &&
        npx puppeteer browsers install chrome &&
        node server.js
      "